<?xml version="1.0" encoding="utf-8"?><Database Name="handheldGames" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\handheldGames.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="handheldGamesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.handheldGames" Member="handheldGames">
    <Type Name="handheldGame">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Handheld" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Publisher" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Rating" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>